# Generated by Django 4.1.6 on 2023-02-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dogs.breed'),
            preserve_default=False,
        ),
    ]
